[package]
name = "rgit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = "0.12.0"
anyhow = "1.0"
axum = { version = "0.6.19", features = ["headers", "macros"] }
axum-macros = "0.3.7"
bat = { version = "0.23.0", default-features = false, features = ["build-assets"] }
bytes = "1.1"
bincode = "1.3"
comrak = "0.18.0"
clap = { version = "4.3.0", features = ["cargo", "derive"] }
futures = "0.3"
git2 = "0.17.2"
hex = "0.4"
nom = "7.1"
md5 = "0.7"
moka = { version = "0.11.1", features = ["future"] }
path-clean = "1.0.1"
parking_lot = "0.12"
serde = { version = "1.0", features = ["derive"] }
syntect = "5"
sled = { version = "0.34", features = ["compression"] }
time = { version = "0.3", features = ["serde"] }
timeago = { version = "0.4.1", default-features = false }
tokio = { version = "1.19", features = ["full"] }
tokio-util = { version = "0.7.3", features = ["io"] }
tower = "0.4"
tower-service = "0.3"
tower-layer = "0.3"
tower-http = { version = "0.4.0", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = "0.3"
unix_mode = "0.1"
uuid = { version = "1.4", features = ["v4"] }
httparse = "1.7"
yoke = { version = "0.7.1", features = ["derive"] }

[build-dependencies]
anyhow = "1.0"
rsass = "0.28.0"
